/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Login;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import Internal.Websocket.Controller.WebsocketController;
import Internal.UserInterface.CustomFrame;

import java.awt.*;

/**
 * @author Suchanan
 */
public class LoginDisplayGUI extends CustomFrame {

    private String username;
    private WebsocketController controller;

    /**
     * Creates new form LoginDisplayGUI
     */
    public LoginDisplayGUI(WebsocketController controller) {
        System.out.println(controller);
        this.controller = controller;
        initComponents();
        this.setTitle("Untitled-Blackjack");
        title.setAlignmentX(Component.CENTER_ALIGNMENT);
    }

    /**
     * This method                                                           is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        InputName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 800));

        loginPanel.setBackground(new java.awt.Color(0, 51, 51));
        loginPanel.setForeground(new java.awt.Color(255, 255, 255));
        loginPanel.setMaximumSize(new java.awt.Dimension(1280, 800));
        loginPanel.setMinimumSize(new java.awt.Dimension(1280, 800));
        loginPanel.setPreferredSize(new java.awt.Dimension(1280, 800));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startButton.setBackground(new java.awt.Color(255, 204, 0));
        startButton.setFont(new java.awt.Font("Book Antiqua", 1, 30)); // NOI18N
        startButton.setText("Start");
        startButton.setMaximumSize(new java.awt.Dimension(400, 60));
        startButton.setMinimumSize(new java.awt.Dimension(400, 60));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        loginPanel.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 400, 60));

        titlePanel.setBackground(new java.awt.Color(0, 0, 0));

        title.setFont(new java.awt.Font("Book Antiqua", 1, 100)); // NOI18N
        title.setForeground(new java.awt.Color(255, 204, 0));
        title.setText("Untitled-BlackJack");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(32, 32, 32))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(title)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        loginPanel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 930, 160));

        InputName.setFont(new java.awt.Font("Book Antiqua", 1, 30)); // NOI18N
        InputName.setMaximumSize(new java.awt.Dimension(400, 60));
        InputName.setMinimumSize(new java.awt.Dimension(400, 60));
        loginPanel.add(InputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 400, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        try {
            // Send auth
            this.username = InputName.getText();
            controller.sendAuth(username);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_startButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputName;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

    public JTextField getInputName() {
        return InputName;
    }

    public void setInputName(JTextField InputName) {
        this.InputName = InputName;
    }

    public JPanel getLoginPanel() {
        return loginPanel;
    }

    public void setLoginPanel(JPanel loginPanel) {
        this.loginPanel = loginPanel;
    }

    public JButton getStartButton() {
        return startButton;
    }

    public void setStartButton(JButton startButton) {
        this.startButton = startButton;
    }

    public void setTitle(JLabel title) {
        this.title = title;
    }

    public JPanel getTitlePanel() {
        return titlePanel;
    }

    public void setTitlePanel(JPanel titlePanel) {
        this.titlePanel = titlePanel;
    }

    public String getUsername() {
        return username;
    }

    @Override
    public void onSwitch() {

    }
}
