import mongoose, { ObjectId } from "mongoose";
import { Card } from "../utils/Card";
import { IGame } from "./GameModel";
import { v4 as uuid } from "uuid";

export interface IUser {
  username: string;
  connectionId?: string;
  sessId: string;
  gameScore: number;
  cards: Card[];
  game: IGame;
}

const UserSchema = new mongoose.Schema({
  /**
   * User choosen name
   */
  username: {
    type: String,
    required: true,
    unqiue: true,
  },
  /**
   * (Secret) Session ID
   * generated by the server, must remain secret to the public
   */
  sessId: {
    type: String,
    default: uuid,
  },
  /**
   * (Secret) Connection ID
   * WS connection ID
   */
  connectionId: {
    type: String,
  },
  gameScore: {
    type: Number,
    default: 0,
  },
  /**
   * Card
   */
  cards: [
    {
      display: {
        type: String,
        required: true,
      },
      values: [
        {
          type: Number,
        },
      ],
    },
  ],
  /**
   * Game
   */
  game: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Game",
  },
  /**
   * Trump Cards
   */
  trumpCards: [
    {
      handler: {
        type: String,
      },
    },
  ],
});

const User = mongoose.model<IUser>("User", UserSchema);
export { User };
